server:
  port: 10000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/blog
  security:
    password-encoder:
      encoding-id: bcrypt
      encoders:
        bcrypt: false
        scrypt: false
        pbkdf2: false
        noop: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.roukaixin.mapper: debug