###
# @name = "账号密码登录"
# @no-log
POST {{baseUrl}}/authentication/login/username/password
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    if (response.status == 200) {
        client.global.set("access_token", response.body.data.accessToken);
    } else {
        client.log(response.body);
    }
%}

###
# @name = "OAuth2 登录"
# @no-log
< {%
    request.variables.set("registrationId", "github")
%}
GET {{baseUrl}}/authentication/oauth2/authorization/{{registrationId}}



###
# @name = "获取 oauth2 登录之后的系统令牌"
# @no-log
< {%
    request.variables.set("registrationId", "github")
    request.variables.set("state", "oqfrtv9j5g98z0p5MWF7_Dzp7IqAnnzSHJFvTs8tKjw=")
%}
POST {{baseUrl}}/authentication/oauth2/token/{{registrationId}}
Content-Type: application/x-www-form-urlencoded

state = {{state}}

> {%
    if (response.status == 200 && response.body.code == 200) {
        client.global.set("access_token", response.body.data.accessToken);
    }
%}


###
# @no-log
# @name = "用户信息"
GET {{baseUrl}}/user/userinfo
Authorization: Bearer {{access_token}}